---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: configvolume
data:
  nginx.conf:
    echo "hello"
---
apiVersion: v1
kind: Pod
metadata:
  name: limiting
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: limiting
    resources:
      requests:
        cpu: "150m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "300Mi"
    volumeMounts:
    - name: nginx-conf
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf #key of configmap data
    ports: 
      - containerPort: 80
  volumes:
  - name: config-vol
    configMap:
      name: configvolume # name of configmap


