apiVersion: v1
kind: Pod
metadata:
  name: livprobe
  namespace: preetam
spec:
  containers:
  - image: nginx
    name: livprobe
    livenessProbe:
      httpGet: 
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 5
      