apiVersion: v1
kind: Pod
metadata:
  name: limiting
  namespace: preetam
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: limiting
    resources:
      cpu: "150m"
      mem: "256Mi"
    limits:
      cpu: "200m"
      memory: "230Mi"
      #stress-ng --help
      
        