apiVersion: v1
kind: Pod
metadata:
  name: limiting
  namespace: preetam
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: limiting
    resources:
      requests:
        cpu: "150m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "300Mi"
        #stress-ng --help  
    


