---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels:
    name: nginx-service
spec:
  containers:
  - image: nginx
    name: web
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
  name: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80      
    
