apiVersion: v1
kind: Pod
metadata:
  name: webserver
  label:
    app: web
spec:
  containers:
    - name: webserver
      image: nginx
      volumeMounts:
        - name: shared-logs
          mounthPath: /var/log/ningx
    - name: sidecar
      image: busybox
      command: ["sh", "-c" , while true; do cat /var/log/nginx/access.log; sleep 30; done"]
      volumeMounts:
        - name: shared-logs
          mounthPath: /var/log/nginx    
   volumes:
     - name: shared-logs
       emptyDir: {}
